// const express = require('express');
// const router = express.Router(); //
// const User = require('../models/user'); //
// const bcrypt = require('bcryptjs'); //
// const jwt = require('jsonwebtoken'); //

// // User registration route
// router.post('/register', async (req, res) => {
//     // Destructure the request body to get name, email, and password
//     try {
//         // Validate input fields
//         const { name, email, password } = req.body; // Destructure the request body to get name, email, and password

//         if (!name || !email || !password) {
//             return res.status(400).json({ message: 'Name, Email and Password are required' });
//         }

//         // check password length
//         if (password.length < 6) {
//             return res.status(400).json({ message: 'Password must be at least 6 characters' });
//         }

//         // Check if user already exists 
//         // User.findOne({ email }) is a Mongoose method that searches the database for a user document with the specified email. 
//         // It returns the first matching document or null if no match is found.
//         const existingUser = await User.findOne({ email });
//         if (existingUser) {
//             return res.status(400).json({ message: 'User already exists' });
//         }

//         // Hash password
//         // bcrypt.genSalt(10) generates a salt with a cost factor of 10, which determines the computational complexity of the 
//         // hashing process. A higher cost factor means more time is required to hash the password, making it more secure against 
//         // brute-force attacks.
//         const salt = await bcrypt.genSalt(10);

//         // bcrypt.hash(password, salt); takes the plain text password and the generated salt, and produces a hashed version of 
//         // the password. This hashed password is what will be stored in the database, ensuring that the original password is not 
//         // exposed even if the database is compromised.
//         const hashedPassword = await bcrypt.hash(password, salt);

//         // Create new user
//         const newUser = await User.create({ name, email, password: hashedPassword });

//         // Generate JWT token
//         // jwt.sign() is a method from the jsonwebtoken library that creates a new JSON Web Token (JWT). 
//         // It takes three arguments: the payload, the secret key, and options such as expiration time.
//         const token = jwt.sign(
//             { userId: newUser._id }, // The payload of the token includes the userId, which is the unique identifier of the newly created user.This allows the server to identify the user in subsequent requests when the token is sent back.
//             process.env.JWT_SECRET, // This secret key is crucial for ensuring the security of the token, as it is used to verify the authenticity of the token when it is sent back to the server in subsequent requests.
//             { expiresIn: '1d' }  // The token will expire in 1 day
//         );

//         res.status(201).json({
//             message: 'User registered successfully',
//             token,
//             user: {
//                 id: newUser._id, // newUser._id is the unique identifier of the newly created user document in the MongoDB database. It is automatically generated by MongoDB when a new document is created and serves as the primary key for that document.
//                 name: newUser.name,
//                 email: newUser.email
//             }
//         });

//     } catch (error) {
//         res.status(500).json({
//             message: 'Server error',
//             error: error.message
//         });
//     }


// });

// // post /api/auth/login
// router.post('/login', async (req, res) => {

//     const { email, password } = req.body;

//     if (!email || !password) {
//         return res.status(400).json({ message: 'Email and Password are required' });
//     }

//     // find the users email

//     const user = await User.findOne({ email });
//     if (!user) {
//         return res.status(400).json({ message: 'Invalid email or password' });
//     }

//     // compare the password with the hashed password in the database
//     const isMatch = await bcrypt.compare(password, user.password); // bcrypt.compare(password, user.password) is a method that compares the plain text password provided by the user during login with the hashed password stored in the database. It returns true if the passwords match and false if they do not.
//     if (!isMatch) {
//         return res.status(400).json({ message: 'Invalid email or password' });
//     }

//     // generate JWT token if the password is correct to authenticate the user for future requests
//     const token = jwt.sign(
//         { userId: user._id },
//         process.env.JWT_SECRET,
//         { expiresIn: '1d' }
//     );

//     res.status(200).json({
//         message: 'Login successful',
//         token,
//         user: {
//             id: user._id,
//             name: user.name,
//             email: user.email
//         }
//     });

// });

// module.exports = router;

// // This file defines the authentication routes for user registration and login.
// // It uses Express to create a router, Mongoose to interact with the User model, bcryptjs for hashing passwords, and jsonwebtoken for
// // generating JWT tokens. The registration route validates input, checks for existing users, hashes the password, creates a new user,
// // and generates a token. The login route validates input, checks for the user's email, compares the provided password with the stored
// // hashed password, and generates a token if authentication is successful. Both routes return appropriate responses based on the outcome
// // of the operations. and importantly, the router is exported for use in the main server file to handle authentication-related requests.

// // why we provide token after registraring user and then also provide another token after logging a user? because after registering a user, we want to immediately authenticate them and allow them to access protected routes without requiring them to log in again. By providing a token upon registration, we can ensure that the user is authenticated right away. However, when the user logs in, we also provide a token to authenticate them for future requests. This way, the user can maintain their authenticated state across different sessions and access protected resources without needing to log in again until the token expires.
// // 

const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/authMiddleware');

const {
    registerUser,
    loginUser
} = require('../controllers/authController');

// 🔐 Auth Routes
router.post('/register', registerUser);
router.post('/login', loginUser);

module.exports = router;